---
  - name: 创建redis存放路径
    file: path={{redis_deposit_path}} state=directory mode=0755
  
  - name: 解压redis
    unarchive: src={{redis_package_name}} dest={{redis_deposit_path}}/
  
  - name: 编译redis
    shell: make && make install  chdir={{redis_deposit_path}}/{{redis_file_name}}
  
  - name: 修改redis配置文件
    template: src=redis.conf.j2 dest={{redis_deposit_path}}/{{redis_file_name}}/redis.conf owner=root group=root mode=0644   
  
  - name: 启动redis server服务
    shell: ./redis-server ../redis.conf  chdir={{redis_deposit_path}}/{{redis_file_name}}/src
